// <auto-generated />
using System;
using DicomMigrator.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DicomMigrator.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617071438_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DicomMigrator.Core.Models.DicomNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("AssociationTimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthUsername")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedSecret")
                        .HasColumnType("text");

                    b.Property<bool>("HasDicomWeb")
                        .HasColumnType("boolean");

                    b.Property<int>("HttpTimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalAet")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("MaxConcurrentAssociations")
                        .HasColumnType("integer");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OperationTimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("QidoBaseUrl")
                        .HasColumnType("text");

                    b.Property<string>("RemoteAet")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RemoteHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RemotePort")
                        .HasColumnType("integer");

                    b.Property<string>("StowBaseUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseTls")
                        .HasColumnType("boolean");

                    b.Property<bool>("ValidateTls")
                        .HasColumnType("boolean");

                    b.Property<string>("WadoBaseUrl")
                        .HasColumnType("text");

                    b.Property<string>("WebBaseUrl")
                        .HasColumnType("text");

                    b.Property<string>("WebQidoPath")
                        .HasColumnType("text");

                    b.Property<string>("WebStowPath")
                        .HasColumnType("text");

                    b.Property<string>("WebWadoPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DicomNodes");
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.DiscoveredStudy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessionNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("DiscoveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DiscoveryJobId")
                        .HasColumnType("integer");

                    b.Property<string>("InstitutionName")
                        .HasColumnType("text");

                    b.Property<string>("IssuerOfPatientId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModalitiesInStudy")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfStudyRelatedInstances")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfStudyRelatedSeries")
                        .HasColumnType("integer");

                    b.Property<string>("PatientBirthDate")
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .HasColumnType("text");

                    b.Property<string>("PatientName")
                        .HasColumnType("text");

                    b.Property<string>("PatientSex")
                        .HasColumnType("text");

                    b.Property<string>("RetrieveAETitle")
                        .HasColumnType("text");

                    b.Property<int>("SourcePacsId")
                        .HasColumnType("integer");

                    b.Property<string>("StudyDate")
                        .HasColumnType("text");

                    b.Property<string>("StudyDescription")
                        .HasColumnType("text");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StudyTime")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ModalitiesInStudy");

                    b.HasIndex("StudyInstanceUid")
                        .IsUnique();

                    b.HasIndex("SourcePacsId", "StudyDate");

                    b.ToTable("DiscoveredStudies");
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.DiscoveryJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DiscoveryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Modalities")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PacsResultLimit")
                        .HasColumnType("integer");

                    b.Property<string>("QueryMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("SourcePacsId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("WorkerThreads")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourcePacsId");

                    b.ToTable("DiscoveryJobs");
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.DiscoveryPartition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<int>("DiscoveryJobId")
                        .HasColumnType("integer");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockedByWorker")
                        .HasColumnType("text");

                    b.Property<string>("Modality")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PartitionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StudiesFound")
                        .HasColumnType("integer");

                    b.Property<int>("StudiesInserted")
                        .HasColumnType("integer");

                    b.Property<int>("StudiesUpdated")
                        .HasColumnType("integer");

                    b.Property<string>("StudyTimeFrom")
                        .HasColumnType("text");

                    b.Property<string>("StudyTimeTo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveryJobId", "Status");

                    b.ToTable("DiscoveryPartitions");
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.DiscoveryRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<int>("DiscoveryJobId")
                        .HasColumnType("integer");

                    b.Property<double>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("Filters")
                        .HasColumnType("text");

                    b.Property<int?>("PartitionId")
                        .HasColumnType("integer");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("SourcePacsId")
                        .HasColumnType("integer");

                    b.Property<int>("StudiesReturned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveryJobId");

                    b.ToTable("DiscoveryRequests");
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.ExecutionWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EnabledDays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("MigrationId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MigrationId")
                        .IsUnique();

                    b.ToTable("ExecutionWindows");
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.LocalConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocalAet")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("LocalHostname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LocalPort")
                        .HasColumnType("integer");

                    b.Property<int>("MaxConcurrentMigrations")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LocalConfigurations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Configuración SCU local por defecto",
                            LocalAet = "MIGRATOR_SCU",
                            LocalHostname = "",
                            LocalPort = 11113,
                            MaxConcurrentMigrations = 3,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.Migration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DestNodeId")
                        .HasColumnType("integer");

                    b.Property<string>("DiscoveryMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InventoryDateFrom")
                        .HasColumnType("text");

                    b.Property<string>("InventoryDateTo")
                        .HasColumnType("text");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<bool>("MigrationAutoPaused")
                        .HasColumnType("boolean");

                    b.Property<string>("ModalityPriority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("OldestFirst")
                        .HasColumnType("boolean");

                    b.Property<int>("OriginNodeId")
                        .HasColumnType("integer");

                    b.Property<int>("RetryDelaySeconds")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StartFromDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TransferMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("VerificationAutoPaused")
                        .HasColumnType("boolean");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkerThreads")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestNodeId");

                    b.HasIndex("OriginNodeId");

                    b.ToTable("Migrations");
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.MigrationAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("MigrationId")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("StudyInstanceUid")
                        .HasColumnType("text");

                    b.Property<string>("TechnicalMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserOrProcess")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MigrationId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("MigrationId", "Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.MigrationStudy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessionNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("DiscoveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuerOfPatientId")
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockedByWorker")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MigrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MigrationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MigrationStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MigrationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ModalitiesInStudy")
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int?>("SourceInstanceCount")
                        .HasColumnType("integer");

                    b.Property<int?>("SourceSeriesCount")
                        .HasColumnType("integer");

                    b.Property<string>("StudyDate")
                        .HasColumnType("text");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("TargetInstanceCount")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetSeriesCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VerificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VerificationStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VerifyLockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifyLockedByWorker")
                        .HasColumnType("text");

                    b.Property<int>("VerifyRetryCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MigrationId", "AccessionNumber")
                        .HasDatabaseName("IX_MigStudies_Mig_Accession");

                    b.HasIndex("MigrationId", "DiscoveryDate")
                        .HasDatabaseName("IX_MigStudies_Mig_DiscDate");

                    b.HasIndex("MigrationId", "MigrationStatus");

                    b.HasIndex("MigrationId", "PatientId")
                        .HasDatabaseName("IX_MigStudies_Mig_Patient");

                    b.HasIndex("MigrationId", "StudyDate")
                        .HasDatabaseName("IX_MigStudies_active")
                        .HasFilter("\"MigrationStatus\" IN ('Pending','RetryPending')");

                    b.HasIndex("MigrationId", "StudyInstanceUid")
                        .IsUnique();

                    b.ToTable("MigrationStudies");
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.DiscoveryJob", b =>
                {
                    b.HasOne("DicomMigrator.Core.Models.DicomNode", "SourcePacs")
                        .WithMany()
                        .HasForeignKey("SourcePacsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourcePacs");
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.DiscoveryPartition", b =>
                {
                    b.HasOne("DicomMigrator.Core.Models.DiscoveryJob", "DiscoveryJob")
                        .WithMany("Partitions")
                        .HasForeignKey("DiscoveryJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscoveryJob");
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.ExecutionWindow", b =>
                {
                    b.HasOne("DicomMigrator.Core.Models.Migration", "Migration")
                        .WithOne("Window")
                        .HasForeignKey("DicomMigrator.Core.Models.ExecutionWindow", "MigrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Migration");
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.Migration", b =>
                {
                    b.HasOne("DicomMigrator.Core.Models.DicomNode", "DestNode")
                        .WithMany("MigrationsAsDest")
                        .HasForeignKey("DestNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DicomMigrator.Core.Models.DicomNode", "OriginNode")
                        .WithMany("MigrationsAsOrigin")
                        .HasForeignKey("OriginNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestNode");

                    b.Navigation("OriginNode");
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.MigrationAuditLog", b =>
                {
                    b.HasOne("DicomMigrator.Core.Models.Migration", "Migration")
                        .WithMany("AuditLogs")
                        .HasForeignKey("MigrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Migration");
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.MigrationStudy", b =>
                {
                    b.HasOne("DicomMigrator.Core.Models.Migration", "Migration")
                        .WithMany("Studies")
                        .HasForeignKey("MigrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Migration");
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.DicomNode", b =>
                {
                    b.Navigation("MigrationsAsDest");

                    b.Navigation("MigrationsAsOrigin");
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.DiscoveryJob", b =>
                {
                    b.Navigation("Partitions");
                });

            modelBuilder.Entity("DicomMigrator.Core.Models.Migration", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Studies");

                    b.Navigation("Window");
                });
#pragma warning restore 612, 618
        }
    }
}
